### ISSUE TITLE
Not all keys are appended with prefix in multi oprations 

### ISSUE THREAD

**Issue by lovelyelfpop** [evansolomon/node-redis-namespace#1]
![qq 20161220182237](https://cloud.githubusercontent.com/assets/5656924/21346896/53054978-c6e1-11e6-9910-f3b9f72c17f1.png)

It's weird, only one key has the prefix 'wis'.
Am I doing something wrong?

**Comment by evansolomon** [comment]
Can you show me the code that leads to the missing prefix?

**Comment by lovelyelfpop** [comment]
[node_redis](https://github.com/NodeRedis/node_redis)  has
support for prefixes builtin. 
See `prefix` option: https://github.com/NodeRedis/node_redis#options-object-properties

**Comment by evansolomon** [comment]
Nice, I'd recommend using that if it works for you
